name: MultiNether
main: com.ymail.MetalsKiller64.MultiNether
version: 0.7
author: MetalsKiller64
description: MultiNether
commands:
  rtp:
    description: Teleportation
    usage: /<command> [x] [y] [z] [welt] [player]
  mn-link:
    description: Verlinke Welt mit Nether
    usage: /<command> [show|add|remove]
    permission: MultiNether.link
    permission-message: Keine Berechtigung!
  mn:
    description: Open or close a portal
    usage: /<command> [create|open|close] [id]
  cmdtest:
    description: Test-Command
    usage: /<command>
    permission: MultiNether.cmdtest
    permission-message: Keine Berechtigung!
